### PR TITLE
Bonnie 2.1 to Master

### PR DESCRIPTION
**Pull request by hossenlopp**
Merging bonnie v2.1 work into master.

Pull requests into Health Data Standards require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.
 
**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass
- [x] Code coverage has not gone down and all code touched or added is covered.

| branch | coverage |
| ------- | --------- |
| master         | 6975 / 7699 LOC (90.6%) covered<br>2692 / 7797 LOC (34.53%) covered |
| bonnie-v2.1 | 6978 / 7702 LOC (90.6%) covered<br>2695 / 7800 LOC (34.55%) covered |

**Cypress Reviewer:**
 
Name:
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases N/A
- [x] You have tried to break the code
 
**Bonnie Reviewer:**
 
Name: @losborne
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

### CODE REVIEW

**Review by lukoktonos — APPROVED** [review]

**Comment by okeefm** [comment]
Where is this `Participation` element coming from? I can't find reference to it in the Model Info File, CQM-models, or elsewhere.

**Comment by hossenlopp** [comment]
@okeefm https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/qdm/src/main/resources/gov/healthit/qdm/qdm-modelinfo-5.3.xml#L22

Refer to #567 for more discussion. This PR is essentially a redo of #567 on to the master_bonnie branch.

**Review by okeefm — APPROVED** [review]
Looks good to me. Identical to #567. Thanks to @hossenlopp for pointing out the location in the Model Info File.

**Comment by edeyoung** [comment]
assuming that o'keefe's approval => all check boxes are checked. Not on bonnie team so not requiring. approving based off of bonnie checkboxes/approval and cypress approval.

**Pull request merged**
