### PR TITLE
NLM authentication

### PR DESCRIPTION
**Pull request by dczulada**

### CODE REVIEW

**Comment by ssayer** [comment]
It looks like this is actually calling out over the network when it does the test. I think it's better to use a WebMock response with this to do the test.

Also there should be a positive and a negative test.

**Comment by okeefm** [comment]
We do some WebMock stuff with testing the ValueSet API, which is similar, in `test/unit/util/vs_api_test.rb`.

**Comment by ssayer** [comment]
:+1:

**Comment by ssayer** [comment]
Rebased and merged into master

**Pull request closed without merging**
