### PR TITLE
Cherry pick ipop

### PR DESCRIPTION
**Pull request by dczulada**

### CODE REVIEW

**Review by okeefm — COMMENTED** [review]
I assume this PR was supposed to pull in more than just the `IPP->IPOP` changes?

**Comment by edeyoung** [comment]
~~this pull request undoes some of the versioning changes that we had merged into master (emailed dave about last week). If your team approves, we would like those changes to persist.~~

Looked too quickly - also, this isn't into master, so ignore :)

**Comment by dczulada** [comment]
sloppy cherry-picking.  this cherry-picks the master commits since the last release.

**Review by okeefm — APPROVED** [review]
Looks good to me.

**Pull request merged**
