### PR TITLE
BONNIE-976 Add profile to valueset

### PR DESCRIPTION
**Pull request by alexanderelliott121**
JIRA: https://jira.mitre.org/browse/BONNIE-976
Test: https://jira.mitre.org/browse/BONNIE-1030

### CODE REVIEW

**Review by c-monkey — APPROVED** [review]
Unit tests here, in bonnie_bunder, and in bonnie pass.

https://jira.mitre.org/browse/BONNIE-1030 passed.

**Review by jbradl11 — APPROVED** [review]
Looks good. Jira Test Passes.

**Comment by lukoktonos** [comment]
Regression script passed--all results are the same.

**Comment by jbradl11** [comment]
I am getting some errors when running `bundle exec rake test`. Specificially `test_api_v2_with_include_draft_default_profile` and `test_api_v2_with_version` (There are others that need to be looked at as well). Maybe you just need to update the tests?

**Comment by holmesie** [comment]
After running the unit tests, I see errors but they don't seem to be related to this work. Some of those include:
```
NoMethodError:         NoMethodError: undefined method `codes' for nil:NilClass
health-data-standards/test/unit/roundtrip/cat_1_roundtrip_test.rb:45:in `test_round_trip'
health-data-standards/test/unit/roundtrip/cat_1_roundtrip_test.rb:45:in `test_round_trip'
```
and
```
Testing Cat I for Mary Berry
  test_schematron_r2_validation                                   FAIL (9.48s)
Minitest::Assertion:         Invalid Cat I for Mary Berry (with header).
        --- expected
        +++ actual
        @@ -1 +1 @@
        -[]
        +[#<ValidationError:0xXXXXXX @location="/*[local-name()='ClinicalDocument' and namespace-uri()='urn:hl7-org:v3']/*[local-name()='component' and namespace-uri()='urn:hl7-org:v3']/*[local-name()='structuredBody' and namespace-uri()='urn:hl7-org:v3']/*[local-name()='component' and namespace-uri()='urn:hl7-org:v3'][3]/*[local-name()='section' and namespace-uri()='urn:hl7-org:v3']", @message="SHALL contain at least one [1..*] entry (CONF:14567).", @validator="QRDA Cat 1 Validator", @file_name="cat1_good.xml">]
```
Are these to be expected?

**Comment by jbradl11** [comment]
Looks like the cql4bonnie branch has 11 failures and 1 error when running unit tests and I am seeing the same results on this branch. So that is "expected".

**Review by holmesie — APPROVED** [review]
All expected tests are passing.

**Review by jbradl11 — APPROVED** [review]
All code looks good. Jira test passes.

**Comment by edeyoung** [comment]
For some reason travis tests are failing and failing locally for james and adam. Same for cql4bonnie and master branches. They pass locally for me and alex. This is something to investigate post 9/12 release.

**Pull request merged**
