### PR TITLE
Support for Ruby 2.4.1.

### PR DESCRIPTION
**Pull request by preston**
As discussed in #498. Travis appears to be barfing due to the inability to write the coverage files, but seems to be working for me locally.

### CODE REVIEW

**Comment by okeefm** [comment]
Also note for the Cypress & Bonnie teams: this will conflict with `mongoid5`, as it bumps `mongoid` from `4.x` to `5.x`.

**Comment by holmesie** [comment]
@okeefm Bonnie will be on mongoid 5.x shortly (https://github.com/projecttacoma/bonnie/pull/724)

**Comment by okeefm** [comment]
@preston It looks like your code is missing some of the updates to comply with the changes from Mongoid 4->5: 

```/home/travis/build/projectcypress/health-data-standards/test/test_helper.rb:18:in `block in <top (required)>': undefined method `sessions=' for Mongoid::Config:Module (NoMethodError)
	from /home/travis/build/projectcypress/health-data-standards/vendor/bundle/ruby/2.4.0/gems/mongoid-5.2.1/lib/mongoid.rb:58:in `configure'
	from /home/travis/build/projectcypress/health-data-standards/test/test_helper.rb:17:in `<top (required)>'
	from /home/travis/build/projectcypress/health-data-standards/test/unit/export/c32_test.rb:1:in `require'
	from /home/travis/build/projectcypress/health-data-standards/test/unit/export/c32_test.rb:1:in `<top (required)>'
	from /home/travis/build/projectcypress/health-data-standards/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:15:in `require'
	from /home/travis/build/projectcypress/health-data-standards/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /home/travis/build/projectcypress/health-data-standards/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/travis/build/projectcypress/health-data-standards/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `<main>'```

The HDS branch at https://github.com/projectcypress/health-data-standards/tree/mongoid5 which Cypress has been running off of has these changes, and so may be a better starting point for this branch. That's where I started my https://github.com/projectcypress/health-data-standards/tree/ruby_24 branch from.

**Comment by holmesie** [comment]
@hossenlopp thoughts?
EDIT: nvm

**Comment by okeefm** [comment]
@holmesie Note: by "your code" I mean the code in the PR, not Bonnie's. Just realized that may have been unclear from my wording.

**Pull request closed without merging**
