### PR TITLE
Add additional information to resolve_provider

### PR DESCRIPTION
**Pull request by rbclark**
This pull request adds support for other applications to access additional data about records assigned to the orphan provider. This will be used by popHealth to log the ID of each record which is assigned to the orphan provider.

### CODE REVIEW

**Comment by rbclark** [comment]
Not sure exactly why travis ci is failing on this, I tested on the exact versions that are showing as failed and did not run into the same issues.

**Comment by okeefm** [comment]
I saw this same issue on a couple of my pull requests last week; Andy was able to fix them by restarting the Travis jobs, but we may want to investigate further why it was happening.

**Comment by okeefm** [comment]
Looks like that was the case here; I restarted the offending jobs, and they passed this time.

**Comment by eedrummer** [comment]
Rebased and merged

**Pull request closed without merging**
