### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jmazella**
Fixing the CCR exporter to handle a procedure with no time field.

### CODE REVIEW

**Comment by projectcypress** [comment]
You are  not authorized to send  mail to the CYPRESS-DEV-LIST  list from your
reply+i-4268474-4035f1bfa190225a0e7f00d8d4f8e6a9cb45fd91-1188796@REPLY.GITHUB.COM
account. You might be authorized to post to the list from another account, or
perhaps when using  another mail program configured to use  a different email
address. However,  LISTSERV has  no way  to associate  this other  account or
address  with yours.  If you  need assistance  or if  you have  any questions
regarding the  policy of the  CYPRESS-DEV-LIST list, please contact  the list
owners at CYPRESS-DEV-LIST-request@LISTS.MITRE.ORG.

**Comment by rdingwell** [comment]
Did you make sure that this still runs the test suit WITH the CCR schema involved in the testing?

**Comment by rdingwell** [comment]
This should also probably use the as_point_in_time method on the entry.  This looks for the time in the various places it may be for the entry.

**Comment by rdingwell** [comment]
One additional thing.  This is a problem in more than just the procedures, it;s in conditions , results , .....  Can you please extrapolate this out into a method that will put the DateTime in the output.  Than update the template sections to just call that method with the current xml builder and the time you want to put in. 

 def to_ccr_date(xml, time)
    if time
         xml.DateTime do
                  xml.Type do
                    xml.Text("Initial Occurrence")
                  end
                  #time
                  xml.ExactDateTime(convert_to_ccr_time_string(time))
                end
          end
end

**Comment by jmazella** [comment]
I changed it like you asked, looks like its working. The CCR export unit test wasn't actually testing anything even if the schema was present, so I replaced the #todo in there with an actual validation check.

**Comment by rdingwell** [comment]
Have you been keeping your repo in sync with the cypress repo?  There is a test in there that does schema validation for CCR export.

**Comment by jmazella** [comment]
Where is that?

**Comment by rdingwell** [comment]
It's in the develop branch in the unit/export/ccr_test.rb

https://github.com/projectcypress/health-data-standards/blob/develop/test/unit/export/ccr_test.rb

**Comment by jmazella** [comment]
oooooh, I'm smart. I was only thinking of the cypress tests. Yes, the health data standards tests pass with the new code.

**Comment by rdingwell** [comment]
yes, but does it  pass with the schema validation enabled?

**Comment by jmazella** [comment]
Yep

**Pull request merged**
