### PR TITLE
Adjusted title and description derivation when parsing MAT 5.3 CQL HQMF exports

### PR DESCRIPTION
**Pull request by holmesie**
Adjusted title and description derivation when parsing MAT 5.3 CQL HQMF exports

JIRA Test: https://jira.mitre.org/browse/BONNIE-917

Related Pull Requests:
https://github.com/projecttacoma/bonnie_bundler/pull/96
https://github.com/projecttacoma/cql_qdm_patientapi/pull/53

### CODE REVIEW

**Comment by lukoktonos** [comment]
Regression test passed.

**Review by lukoktonos — APPROVED** [review]
Passed regression test.

**Review by hossenlopp — APPROVED** [review]
Manual JIRA tests pass. Code looks good and properly explains its necessity.

**Review by c-monkey — APPROVED** [review]
Test https://jira.mitre.org/browse/BONNIE-917 passed.
https://oncprojectracking.healthit.gov/support/browse/BONNIE-277 is resolved.
https://oncprojectracking.healthit.gov/support/browse/BONNIE-326 is resolved.

**Pull request merged**
