### PR TITLE
Transfer dates need to be shifted when an encounter is shifted

### PR DESCRIPTION
**Pull request by dczulada**

### CODE REVIEW

**Comment by c-monkey** [comment]
@dczulada Please persuade me not to outright fail this with no tests. To make me most happy, there would be automated regression tests that would fail if this change were not implemented.

Thanks,
--Chris

**Comment by dczulada** [comment]
@c-monkey unit test added

**Review by c-monkey — APPROVED** [review]
These unit tests are good. Approved.

**Review by okeefm — APPROVED** [review]
Tested, transfers are properly being shifted into the reporting period. Approved.

**Pull request merged**
