### PR TITLE
added act wrapper templates to encounter, transfers and medication di…

### PR DESCRIPTION
**Pull request by dczulada**
…spense

### CODE REVIEW

**Comment by dczulada** [comment]
These changes would still need to be incorporated into the QRDA 3.1 Branch

**Review by okeefm — APPROVED** [review]
Looks good to me.

**Comment by okeefm** [comment]
Question: should we worry about the CodeClimate "similar code" issues? Or the complex method issue?

**Comment by ssayer** [comment]
There might be a better meta-programming way to get rid of the duplicate code, since the only real difference between the new importers is the parent class and the XPath. Whether it's worth the effort to do that, I'm not sure. The initialize method is already a tire fire, you're just adding more tires :)

I'm not sure if the effort to refactor here is worth the time it will take, but these are things to think about/fix in the Go implementation.

**Pull request closed without merging**
