### PR TITLE
Feature/mat 786 gitleaks automation

### PR DESCRIPTION
**Pull request by casey-erdmann**
Pull requests into Health Data Standards require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.
 
This PR adds the automated secret scanner gitleaks to the project to insure future branches and commits are scanned for potential sensitive leaked information on push.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] Internal ticket for this PR: MAT-786
- [x] Internal ticket links back to this PR - N/A
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases - N/A
- [x] Tests have been run locally and pass - N/A
- [x] Code coverage has not gone down and all code touched or added is covered. - N/A
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: N/A not a code change
         2. Add TODOs in the code noting that it requires a test - N/A
         3. Add a JIRA task to add the test and link it here: - N/A
 
**Cypress Reviewer:**
 
Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code
 
**Bonnie Reviewer:**
 
Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Review by adongare — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by casey-erdmann** [comment]
@AndrewBird81 any reason Travis CI is hung on this one?

**Comment by adongare** [comment]
@AndrewBird81 According to travis documentation repositories are tied to their organization. Since we moved this to new organization we need to activate this in travis. Can I add Measure Authoring Tool org to travis ci?

**Comment by adongare** [comment]
@casey-erdmann Build is fixed now and can be merged. I'm not sure how to remove that old build hanging there forever(could be permission issue).

**Comment by casey-erdmann** [comment]
I'll try and push up a new copy and see if it resolves itself.

**Pull request merged**
