### PR TITLE
Add bundler-audit and update gems to comply

### PR DESCRIPTION
**Pull request by tstrass**
bundler-audit identifies gem versions with known vulnerabilities.

This adds bundler-audit to the project and brings HDS into compliance.
Previously out of compliance: nokogiri, activemodel, rubyzip

Note that the [`zip-zip`](https://github.com/orien/zip-zip) gem was added because `rubyzip` needed to be updated to a version that changed their API, and `zip-zip` is apparently a way to make it backwards compatible.

### CODE REVIEW

**Comment by tstrass** [comment]
I did not add `bundler-audit` to Travis, but I can add that in if reviewers want it

**Review by dczulada — APPROVED** [review]
Looks good

**Review by edeyoung — COMMENTED** [review]
Someone from the Bonnie team needs to test this to make sure it doesn't mess things up for us. I'll mention it at standup today and then assign someone (both at standup and on the ticket).

**Comment by edeyoung** [comment]
Initial pass shows there are some conflicts with bonnie that are non-trivial to address. @hossenlopp is looking into it.

**Review by okeefm — CHANGES_REQUESTED** [review]
Regardless of the Bonnie reviews, I would suggest that if we're using Bundler-audit, it should be in Travis.

**Review by okeefm — APPROVED** [review]
Travis change looks good to me.

**Pull request closed without merging**
